try {
  output(10);
} catch (err) {
} finally {
}

try {
  output(10);
} finally {
}
